:USER_GUID: %GUID%
:USERNAME: %USERNAME%
:markup-in-source: verbatim,attributes,quotes
:show_solution: true


== Overview


This workshop is designed to show application developers how to incorporate machine learning workflows into their everyday engineering discipline.  Our goal is for developers who are excited about machine learning to learn three important things in the context of a real application, namely detecting spam messages:

- how to use machine learning to solve a real problem, from visualization to a deployable model that can run as an application component;
- how to evaluate and validate predictive models, and some metrics that are more useful than raw accuracy;
- how OpenShift enables every stage of machine learning discovery and production, including trying different approaches to solve a problem.

Enjoy!
== User Information

Here is your user information:

[source,bash,options="nowrap",subs="{markup-in-source}"]
----
Here is some important information about your environment:

Your GUID is: *{USER_GUID}*

Your username is: *{USERNAME}*

----